### ISSUE TITLE
bad argument #2 to 'split' 

### ISSUE THREAD

**Issue by Monteo** [Aviana/HealComm#20] opened 2019-09-15 07:33 UTC
1x ...bs\LibClassicHealComm-1.0\LibClassicHealComm-1.0-19.lua:1679: bad argument #2 to 'split' (string expected, got nil)
[C]: in function `split'
...bs\LibClassicHealComm-1.0\LibClassicHealComm-1.0-19.lua:1679: in function `?'
...bs\LibClassicHealComm-1.0\LibClassicHealComm-1.0-19.lua:2073: in function <...bs\LibClassicHealComm-1.0\LibClassicHealComm-1.0.lua:2072>

Locals:
(*temporary) = ","
(*temporary) = nil
(*temporary) = "string expected, got nil"

**Comment by Aviana** [comment] 2019-09-30 13:07
Duplicate of https://github.com/Aviana/LibClassicHealComm-1.0/issues/3#issue-499739414

**Closed by Aviana** 2019-09-30 13:07 UTC
